borg-mount: Allow to re-run instead of exiting; minor fixes

diff --git a/.local/bin/borg-mount b/.local/bin/borg-mount
--- a/.local/bin/borg-mount
+++ b/.local/bin/borg-mount
@@ -22,7 +22,7 @@ if ! command -v borg >/dev/null; then
 fi
 
 if [[ $# -ne 1 ]]; then
-	printf "Usage: %s repo" "$script_name"
+	printf "Usage: %s repo\n" "$script_name"
 	exit 1
 fi
 
@@ -39,34 +39,43 @@ if ! archives=$(borg list --short "$repo"); then
 	exit 1
 fi
 
-printf "Select archive:\n"
-select archive in ALL ${archives}; do
-	case ${archive} in
-		"") printf "Invalid archive.\n" ;;
-		*) printf "You selected %s.\n\n" "${archive}" && break ;;
-	esac
+while true; do
+	printf "Select archive:\n"
+	select archive in ALL ${archives}; do
+		case ${archive} in
+			"") printf "Invalid archive.\n" ;;
+			*) printf "You selected %s.\n\n" "${archive}" && break ;;
+		esac
+	done
+
+	if [[ "$archive" == "ALL" ]]; then
+		src="${repo}"
+	else
+		src="${repo}::${archive}"
+	fi
+
+	mnt_dir=$(mktemp -d)
+	printf "Mounting at %s...\n" "${mnt_dir}"
+	if ! borg "${common_options[@]}" mount "${options[@]}" "${src}" "${mnt_dir}"; then
+		printf "Error mounting.\n"
+		exit 1
+	fi
+
+	if [ -n "${DISPLAY:-}" ]; then
+		printf "Opening in file manager...\n\n"
+		exec "${file_manager[@]}" "${mnt_dir}" > /dev/null 2>&1 & disown
+	fi
+
+	read -p "Press enter to umount. "
+	while ! fusermount -u "${mnt_dir}"; do
+		read -p "Press enter to try again. "
+	done
+	rmdir "$mnt_dir"
+
+	printf "\n"
+	read -r -n 1 -p "Press any key to mount another archive. Press q to exit. " loop
+	printf "\n"
+	if [[ "${loop,,}" == "q" ]]; then
+		break
+	fi
 done
-
-if [[ "$archive" == "ALL" ]]; then
-	src="${repo}"
-else
-	src="${repo}::${archive}"
-fi
-
-mnt_dir=$(mktemp -d)
-printf "Mounting at %s...\n" "${mnt_dir}"
-if ! borg "${common_options[@]}" mount "${options[@]}" "${src}" "${mnt_dir}"; then
-	printf "Error mounting.\n"
-	exit 1
-fi
-
-if [ -n "${DISPLAY:-}" ]; then
-	printf "Opening in file manager...\n\n"
-	exec "${file_manager[@]}" "${mnt_dir}" & disown
-fi
-
-read -p "Press enter to umount. "
-while ! fusermount -u "${mnt_dir}"; do
-	read -p "Press enter to try again. "
-done
-rmdir "$mnt_dir"
