borg-mount: Allow mouting entire repository

diff --git a/.local/bin/borg-mount b/.local/bin/borg-mount
--- a/.local/bin/borg-mount
+++ b/.local/bin/borg-mount
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #
-# Mount Borg archives with ease.
+# Mount Borg archives and repos with ease.
 #
-# Copyright (C) 2019-2022 Rafael Cavalcanti <https://rafaelc.org/dev>
+# Copyright (C) 2019-2023 Rafael Cavalcanti <https://rafaelc.org/dev>
 # Licensed under GPLv3
 
 set -euo pipefail
@@ -34,23 +34,29 @@ if [[ -z "${BORG_PASSPHRASE:-}" && -z "${BORG_PASSCOMMAND:-}" && -z "${BORG_PASS
 	export BORG_PASSPHRASE
 fi
 
-printf "Select archive:\n"
 if ! archives=$(borg list --short "$repo"); then
 	printf "Error listing archives.\n"
 	exit 1
 fi
-select archive in ${archives}; do
+
+printf "Select archive:\n"
+select archive in ALL ${archives}; do
 	case ${archive} in
 		"") printf "Invalid archive.\n" ;;
 		*) printf "You selected %s.\n\n" "${archive}" && break ;;
 	esac
 done
 
+if [[ "$archive" == "ALL" ]]; then
+	src="${repo}"
+else
+	src="${repo}::${archive}"
+fi
+
 mnt_dir=$(mktemp -d)
-printf "Mounting archive at %s...\n" "${mnt_dir}"
-if ! borg "${common_options[@]}" mount "${options[@]}" \
-		"${repo}::${archive}" "${mnt_dir}"; then
-	printf "Error mounting archive.\n"
+printf "Mounting at %s...\n" "${mnt_dir}"
+if ! borg "${common_options[@]}" mount "${options[@]}" "${src}" "${mnt_dir}"; then
+	printf "Error mounting.\n"
 	exit 1
 fi
 
