light-dark: Use spaces instead of tabs

diff --git a/.local/bin/light-dark b/.local/bin/light-dark
--- a/.local/bin/light-dark
+++ b/.local/bin/light-dark
@@ -10,93 +10,93 @@ readonly config_keys=("theme_light" "theme_dark")
 readonly xsettingsd_config="$HOME/.config/xsettingsd/xsettingsd.conf"
 
 main() {
-	if [[ $# -ne 1 ]]; then
-		usage
-	fi
+  if [[ $# -ne 1 ]]; then
+    usage
+  fi
 
-	check_desktop
-	get_config
-	set_target "$1"
-	apply
+  check_desktop
+  get_config
+  set_target "$1"
+  apply
 }
 
 usage() {
-	printf "Usage: %s<light|dark|toggle>\n" "$(basename "$0")"
-	exit 1
+  printf "Usage: %s<light|dark|toggle>\n" "$(basename "$0")"
+  exit 1
 }
 
 log() {
-	printf "%s\n" "$*" 1>&2
+  printf "%s\n" "$*" 1>&2
 }
 
 get_config() {
-	[[ -e "$config_path" ]] || create_config
-	source "$config_path"
-	check_config
+  [[ -e "$config_path" ]] || create_config
+  source "$config_path"
+  check_config
 }
 
 create_config() {
-	log "Creating config at %s. Edit it and run again.\n" "${config_path/$HOME/\~}"
-	for key in "${config_keys[@]}"; do
-		printf "%s=\n" "$key" >> "$config_path"
-	done
-	exit 1
+  log "Creating config at %s. Edit it and run again.\n" "${config_path/$HOME/\~}"
+  for key in "${config_keys[@]}"; do
+    printf "%s=\n" "$key" >> "$config_path"
+  done
+  exit 1
 }
 
 check_config() {
-	for key in "${config_keys[@]}"; do
-		if [[ -z "${!key}" ]]; then
-			log "%s not found in config file." "$key"
-			exit 1
-		fi
-	done
+  for key in "${config_keys[@]}"; do
+    if [[ -z "${!key}" ]]; then
+      log "%s not found in config file." "$key"
+      exit 1
+    fi
+  done
 }
 
 check_desktop() {
-	if ! pidof xsettingsd > /dev/null; then
-		log "This desktop is not supported."
-	fi
+  if ! pidof xsettingsd > /dev/null; then
+    log "This desktop is not supported."
+  fi
 }
 
 set_target() {
-	case "${1:-}" in
-		light)
-			readonly target_theme="$theme_light"
-			readonly target_scheme="prefer-light"
-			;;
-  	dark)
-			readonly target_theme="$theme_dark"
-			readonly target_scheme="prefer-dark"
-			;;
-		toggle)
-			set_target_toggle
-			;;
-		*)
-		usage
-	esac
+  case "${1:-}" in
+    light)
+      readonly target_theme="$theme_light"
+      readonly target_scheme="prefer-light"
+      ;;
+    dark)
+      readonly target_theme="$theme_dark"
+      readonly target_scheme="prefer-dark"
+      ;;
+    toggle)
+      set_target_toggle
+      ;;
+    *)
+    usage
+  esac
 }
 
 set_target_toggle() {
-	local -r theme_current="$(awk -F' ' '/^Net\/ThemeName / {gsub("\"","", $2); print $2}' "$xsettingsd_config")"
+  local -r theme_current="$(awk -F' ' '/^Net\/ThemeName / {gsub("\"","", $2); print $2}' "$xsettingsd_config")"
 
-	case "$theme_current" in
-		$theme_light) set_target "dark" ;;
-		$theme_dark) set_target "light" ;;
-	esac
+  case "$theme_current" in
+    $theme_light) set_target "dark" ;;
+    $theme_dark) set_target "light" ;;
+  esac
 }
 
 apply() {
-	# xsettingsd
-	sed -i "s#^Net/ThemeName .*\$#Net/ThemeName \"$target_theme\"#" "$xsettingsd_config"
-	killall -HUP xsettingsd
+  # xsettingsd
+  sed -i "s#^Net/ThemeName .*\$#Net/ThemeName \"$target_theme\"#" "$xsettingsd_config"
+  killall -HUP xsettingsd
 
-	# Set theme on gnome
-	# This is relevant on dwm because:
-	# - prefer-dark sets some gnome applications to dark.
-	# - gtk-theme (used for theming "legacy" apps) sets Qt
-	# applications dark, since we are using qgnomeplatform.
-	gsettings set org.gnome.desktop.interface gtk-theme "'$target_theme'"
-	gsettings set org.gnome.desktop.interface color-scheme "'$target_scheme'"
+  # Set theme on gnome
+  # This is relevant on dwm because:
+  # - prefer-dark sets some gnome applications to dark.
+  # - gtk-theme (used for theming "legacy" apps) sets Qt
+  # applications dark, since we are using qgnomeplatform.
+  gsettings set org.gnome.desktop.interface gtk-theme "'$target_theme'"
+  gsettings set org.gnome.desktop.interface color-scheme "'$target_scheme'"
 }
 
 main "$@"
