timew-rename-tag: Check if old tag exists
Not checking would tag the last period with the new tag.

diff --git a/.local/bin/timew-rename-tag b/.local/bin/timew-rename-tag
--- a/.local/bin/timew-rename-tag
+++ b/.local/bin/timew-rename-tag
@@ -2,12 +2,18 @@
 #
 # rename timewarrior tag: use as timew-tagrename <oldtag> <newtag>
 #
-# Downloaded from https://github.com/GothenburgBitFactory/timewarrior/issues/210#issuecomment-594799967
+# Adapted from https://github.com/GothenburgBitFactory/timewarrior/issues/210#issuecomment-594799967
+# by Rafael Cavalcanti - rafaelc.org.
 
 oldtag=$1; shift
 newtag=$1; shift
 idlist=$(timew summary 1970W01 - now "$oldtag" :ids |\
   sed -nr 's/.* (@[0-9]+) .*/\1/p')
+
+if [[ -z $idlist ]]; then
+  echo "Old tag not found."
+  exit 1
+fi
 
 timew tag $idlist "$newtag"
 timew untag $idlist "$oldtag"
