update: Prompt user on more updates and some fixes

diff --git a/.local/bin/update b/.local/bin/update
--- a/.local/bin/update
+++ b/.local/bin/update
@@ -23,11 +23,11 @@ main() {
 	update_repos
 	update_dotfiles
 
-	log "Script concluído."
+	log "Concluído."
 }
 
 log() {
-	printf "\n\n%s\n" "$*" 1>&2
+	printf "\n%s\n" "$*" 1>&2
 }
 
 log_os() {
@@ -39,7 +39,29 @@ log_step() {
 	log "[ $step ] $*"
 }
 
+# args: prompt
+# exit codes: 0 if yes, 1 if no
+ask() {
+	local -r prompt="$1"
+
+	printf "\n"
+	read -r -n 1 -p "> $prompt " answer
+	if [[ ! "$answer" =~ [yYsS] ]]; then
+		log "Pulando..."
+		return 1
+	fi
+
+	return 0
+}
+
+# Workaround for syntax error
+yadm() {
+	bash "$HOME/.local/bin/yadm" "$@"
+}
+
 update_distro() {
+	ask "Atualizar pacotes da distro?" || return 0
+
 	# Update distro packages - order matters
 	if is_osmc; then
 		log_os "OSMC"
@@ -84,7 +106,6 @@ update_distro_osmc() {
 
 	1) Add-on do OSMC (recomendado)
 	2) APT
-	3) Não atualizar
 
 	END
 
@@ -101,14 +122,12 @@ update_distro_osmc() {
 		2)
 			update_distro_apt
 			;;
-		3)
-			log "Pulando atualização dos pacotes..."
-			;;
 	esac
 }
 
 update_flatpaks() {
 	has_command flatpak || return 0
+	ask "Atualizar flatpaks?" || return 0
 
 	flatpak update
 }
@@ -154,17 +173,12 @@ update_zinit() {
 	has_command zsh || return 0
 
 	log_step "Atualizando zsh zinit..."
-	zsh -ic "zinit update --parallel"
+	zsh -ic "zinit update --parallel" || true
 }
 
 update_submodules() {
 	has_command yadm || return 0
-
-	read -n 1 -p "Atualizar submódulos yadm? " answer
-	if [[ ! "$answer" =~ [yYsS] ]]; then
-		log "Pulando..."
-		return
-	fi
+	ask "Atualizar submódulos dos dotfiles?" || return 0
 
 	log_step "Atualizando submódulos yadm..."
 	yadm submodule update --recursive --remote
