obsidian-repo: Change order of git operations and check empty commit

diff --git a/.shortcuts/obsidian-repo b/.shortcuts/obsidian-repo
--- a/.shortcuts/obsidian-repo
+++ b/.shortcuts/obsidian-repo
@@ -39,6 +39,65 @@ get_device_name() {
   echo ${android_device:-Termux}
 }
 
+clone_repo() {
+  # Might make it faster
+  termux-wake-lock
+
+  git clone --separate-git-dir="$git_dir" "$repo_url" "$work_tree"
+  echo "gitdir: $git_dir" > "$work_tree/.git"
+
+  termux-wake-unlock
+}
+
+stage() {
+  if [[ -z "$(git_cmd status --porcelain)" ]]; then
+    log "Repositório limpo. Staging não é necessário."
+    return
+  fi
+
+  log "Staging:"
+  echo "Press ENTER to stage files in lazygit."
+  echo "Don't commit or push: it'll be done automatically."
+  read
+  lazygit --git-dir "$git_dir" --work-tree "$work_tree"
+}
+
+commit() {
+  if git_cmd diff --cached --quiet; then
+    echo "Nothing to commit."
+    return
+  fi
+
+  log "Commiting..."
+  git_cmd commit --stat --verbose --message="Update on $(get_device_name): $(date '+%Y-%m-%d %H:%M:%S')"
+}
+
+pull() {
+  log "Pulling..."
+  if ! git_cmd pull --rebase; then
+    echo "Failed."
+    read
+  fi
+}
+
+push() {
+  log "Pushing..."
+  git_cmd push
+}
+
+main() {
+  if [[ ! -d "$git_dir" || ! -d "$work_tree" ]] then
+    printf "Repo not found. Cloning...\n"
+    clone_repo
+  fi
+
+  stage
+  commit
+  pull
+  push
+}
+
+
 cat << "EOF"
        _         _     _ _
   ___ | |__  ___(_) __| (_) __ _ _ __
@@ -58,34 +117,4 @@ Designed to be used on mobile devices' Termux.
 
 EOF
 
-
-if [[ ! -d "$git_dir" || ! -d "$work_tree" ]] then
-  printf "Repo not found. Cloning...\n"
-
-  # Might make it faster
-  termux-wake-lock
-
-  git clone --separate-git-dir="$git_dir" "$repo_url" "$work_tree"
-  echo "gitdir: $git_dir" > "$work_tree/.git"
-
-  termux-wake-unlock
-fi
-
-log "Pulling..."
-git_cmd pull
-
-if [[ -z "$(git_cmd status --porcelain)" ]]; then
-  log "Repositório limpo. Commit não é necessário."
-else
-  log "Manual staging..."
-  echo "Press ENTER to stage files in lazygit."
-  echo "Don't commit or push: it'll be done automatically."
-  read
-  lazygit --git-dir "$git_dir" --work-tree "$work_tree"
-
-  log "Commiting..."
-  git_cmd commit --stat --verbose --message="Update on $(get_device_name): $(date '+%Y-%m-%d %H:%M:%S')"
-fi
-
-log "Pushing..."
-git_cmd push
+main "$@"
